/* //device/libs/telephony/ril_unsol_commands.h
**
** Copyright 2006, The Android Open Source Project
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
*/
    {RIL_UNSOL_RESPONSE_RADIO_STATE_CHANGED, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_RESPONSE_CALL_STATE_CHANGED, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_RESPONSE_VOICE_NETWORK_STATE_CHANGED, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_RESPONSE_NEW_SMS, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_RESPONSE_NEW_SMS_STATUS_REPORT, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_RESPONSE_NEW_SMS_ON_SIM, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_ON_USSD, responseStrings, WAKE_PARTIAL},
    {RIL_UNSOL_ON_USSD_REQUEST, responseVoid, DONT_WAKE},
    {RIL_UNSOL_NITZ_TIME_RECEIVED, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_SIGNAL_STRENGTH, responseRilSignalStrength, DONT_WAKE},
    {RIL_UNSOL_DATA_CALL_LIST_CHANGED, responseDataCallList, WAKE_PARTIAL},
    {RIL_UNSOL_SUPP_SVC_NOTIFICATION, responseSsn, WAKE_PARTIAL},
    {RIL_UNSOL_STK_SESSION_END, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_STK_PROACTIVE_COMMAND, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_STK_EVENT_NOTIFY, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_STK_CALL_SETUP, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_SIM_SMS_STORAGE_FULL, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_SIM_REFRESH, responseSimRefresh, WAKE_PARTIAL},
    {RIL_UNSOL_CALL_RING, responseCallRing, WAKE_PARTIAL},
    {RIL_UNSOL_RESPONSE_SIM_STATUS_CHANGED, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_RESPONSE_CDMA_NEW_SMS, responseCdmaSms, WAKE_PARTIAL},
    {RIL_UNSOL_RESPONSE_NEW_BROADCAST_SMS, responseRaw, WAKE_PARTIAL},
    {RIL_UNSOL_CDMA_RUIM_SMS_STORAGE_FULL, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_RESTRICTED_STATE_CHANGED, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_ENTER_EMERGENCY_CALLBACK_MODE, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_CDMA_CALL_WAITING, responseCdmaCallWaiting, WAKE_PARTIAL},
    {RIL_UNSOL_CDMA_OTA_PROVISION_STATUS, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_CDMA_INFO_REC, responseCdmaInformationRecords, WAKE_PARTIAL},
    {RIL_UNSOL_OEM_HOOK_RAW, responseRaw, WAKE_PARTIAL},
    {RIL_UNSOL_RINGBACK_TONE, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_RESEND_INCALL_MUTE, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_CDMA_SUBSCRIPTION_SOURCE_CHANGED, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_CDMA_PRL_CHANGED, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_EXIT_EMERGENCY_CALLBACK_MODE, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_RIL_CONNECTED, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_VOICE_RADIO_TECH_CHANGED, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_CELL_INFO_LIST, responseCellInfoList, WAKE_PARTIAL}, // 1036
    {RIL_UNSOL_RESPONSE_IMS_NETWORK_STATE_CHANGED, responseVoid, WAKE_PARTIAL},
    {1038, NULL, WAKE_PARTIAL},
    {1039, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_ON_SS, responseSSData, WAKE_PARTIAL},
    {1041, NULL, WAKE_PARTIAL},
    {1042, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_DUN_INFO, responseStrings, WAKE_PARTIAL},
#if 0
    {RIL_UNSOL_SIM_APPLICATION_REFRESH, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_STK_CALL_SETUP_STATUS, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_STK_CALL_SETUP_RESULT, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_STK_SEND_SM_STATUS, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_STK_SEND_SM_RESULT, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_STK_SEND_USSD_RESULT, responseString, WAKE_PARTIAL},
#endif
    {RIL_UNSOL_RELEASE_COMPLETE_MESSAGE, responseSSReleaseCompleteNotification, WAKE_PARTIAL},/*???*/
    {RIL_UNSOL_STK_SEND_SMS_RESULT, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_STK_CALL_CONTROL_RESULT, responseString, WAKE_PARTIAL},/*???*/
    {RIL_UNSOL_DUN_CALL_STATUS, responseInts, WAKE_PARTIAL},
    {11005, NULL, WAKE_PARTIAL},
    {11006, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_O2_HOME_ZONE_INFO, responseInts, WAKE_PARTIAL},/*???*/
    {RIL_UNSOL_DEVICE_READY_NOTI, responseVoid, WAKE_PARTIAL},/*???*/
    {RIL_UNSOL_GPS_NOTI, responseVoid, WAKE_PARTIAL},/*???*/
    {RIL_UNSOL_AM, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_DUN_PIN_CONTROL_SIGNAL, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_DATA_SUSPEND_RESUME, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_SAP, responseVoid, WAKE_PARTIAL},
    {11014, NULL, WAKE_PARTIAL},
    {11015, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_HSDPA_STATE_CHANGED, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_WB_AMR_STATE, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_TWO_MIC_STATE, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_DHA_STATE, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_UART, responseRaw, WAKE_PARTIAL},/*???*/
    {RIL_UNSOL_SIM_PB_READY, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_PCMCLOCK_STATE, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_1X_SMSPP, responseRaw, WAKE_PARTIAL},
    {11024, responseRaw, WAKE_PARTIAL},/*???*/
    {11025, NULL, WAKE_PARTIAL},
    {11026, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_IMS_REGISTRATION_STATE_CHANGED, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_MODIFY_CALL, responseCallModify, WAKE_PARTIAL},
    {RIL_UNSOL_SRVCC_HANDOVER, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_CS_FALLBACK, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_UICC_SUBSCRIPTION_STATUS_CHANGED, responseInts, WAKE_PARTIAL},
    {UNSOL_VOICE_SYSTEM_ID, responseInts, WAKE_PARTIAL},
    {11033, responseVoid, WAKE_PARTIAL},/*???*/
    {RIL_UNSOL_IMS_RETRYOVER, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_STK_ALPHA_ID, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_PB_INIT_COMPLETE, responseVoid, WAKE_PARTIAL},
    {11037, NULL, WAKE_PARTIAL},
    {11038, NULL, WAKE_PARTIAL},
    {11039, NULL, WAKE_PARTIAL},
    {11040, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_RTS_INDICATION, responseStrings, WAKE_PARTIAL},
    {RIL_UNSOL_RILD_RESET_NOTI, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_HOME_NETWORK_NOTI, responseVoid, WAKE_PARTIAL},
    {11044, NULL, WAKE_PARTIAL},
    {RIL_UNSOL_OMADM_SEND_DATA, responseVoid, WAKE_PARTIAL},
    {RIL_UNSOL_DUN, responseString, WAKE_PARTIAL},
    {RIL_UNSOL_SYSTEM_REBOOT, responseVoid, WAKE_PARTIAL},
    {11048, NULL, WAKE_PARTIAL},    
    {RIL_UNSOL_UTS_GETSMSCOUNT, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_UTS_GETSMSMSG, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_UTS_GET_UNREAD_SMS_STATUS, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_MIP_CONNECT_STATUS, responseInts, WAKE_PARTIAL},
    {RIL_UNSOL_STK_CALL_STATUS, responseInts, WAKE_PARTIAL},
    /*{RIL_UNSOL_CP_ASSERTED_OR_RESETTING, responseVoid, WAKE_PARTIAL},*/
